### ISSUE TITLE
lenient_late doesn't appear to work

### ISSUE THREAD

**Issue by BenMusch** [jolynch/mit-tab#112]
Two tournaments have reported issues with the setting. We should:

 - Make sure the current implementation of lenient_late works. Fix it if it doesn't
 - Improve the documentation & usability around that. The `NoShow` model doesn't really surface itself in the UI. It should.

**Comment by BenMusch** [comment]
I think we just need something like this for pairing in teams in the middle of the 0-1: https://github.com/jolynch/mit-tab/blob/master/mittab/libs/tab_logic.py#L94

**Comment by ifly6** [comment]
What do you mean by it doesn't appear to work? Is it the problem that emerged when the `lenient_late` setting didn't appear in the database (for, unclear to me, reasons) or is it that `lenient_late` _the feature_ doesn't work?

**Comment by BenMusch** [comment]
lenient_late feature doesn't work, people are paired into the bottom of the bracket when they should be in the middle. This PR fixes it: https://github.com/jolynch/mit-tab/pull/113

**Comment by BenMusch** [comment]
Fixed: https://github.com/jolynch/mit-tab/pull/113
