### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by ifly6** [jolynch/mit-tab#114]
It would be great to be able to export the database to Excel. I know last year, GW used a custom break based on some formula involving speaks, opp_strength, etc.

I think I wrote code to do that some time ago, but it would require that there be changes to the views as well, adding a new screen for exporting to Excel. I also wrote functions to export the rooms and judges along with the teams. 

My apologies to Ben, but I haven't really been keeping up with the changes he's been making, and I'm not sure whether the changes which I forked off (from nearly a year ago) are still compatible. If I were sure of that, I'd just up and do it.

**Comment by ifly6** [comment]
I think my pull request does that here: https://github.com/ifly6/mit-tab/blob/75399b436d3a852b6f6759252e7d987b81e83df8/mittab/libs/data_import/export_xls_files.py

**Comment by BenMusch** [comment]
It does -- I'll try to review & update that this weekend

**Comment by BenMusch** [comment]
Duplicate of https://github.com/jolynch/mit-tab/issues/30
