### ISSUE TITLE
Persistent tab director logins across tournaments

### ISSUE THREAD

**Issue by andrewmin** [jolynch/mit-tab#36]
This is probably a pretty big undertaking, but it'd be awesome if you could have a tab director have a login he always gets access to. Reasons this would be cool:
1. you could restore custom settings.
2. you could load saved tab scratches, rather than having to remember every tab scratch every time. If it's been justified to you once, you'll probably accept it again.
3. you could load saved judge scores. Not only is this very useful for good judges, it could also be very useful for bad judges (you may have forgotten that rando novice was absolutely terrible at judging and should be ranked even worse than the other novices).

**Comment by BenMusch** [comment]
Closing this -- it's not really possible with the way mittab is written. There has to be a separate server for each tournament, so "centralization" of logins would require rewriting the majority of the application
