### ISSUE TITLE
Fix drag-and-drop in pairings

### ISSUE THREAD

**Issue by andrewmin** [jolynch/mit-tab#37]
People will often try to copy and paste the table from pairings (for example, to examine motion fairness). However, it's very easy to accidentally drag and drop a team instead of selecting, which results in teams being swapped from their rounds. Solutions:
1. disable drag and drop permanently
2. have an option to toggle drag and drop
3. (probably most optimal, if possible): have an undo button

**Comment by BenMusch** [comment]
https://github.com/jolynch/mit-tab/pull/100
