### ISSUE TITLE
No instructions/information on what the default admin account is once MIT-Tab is initialized

### ISSUE THREAD

**Issue by yazhao** [jolynch/mit-tab#44]
After going through the readme instructions to get MIT-Tab running locally on my computer, I'm able to get to the login screen, but don't know what/where to find the default admin account to login with.

**Comment by jolynch** [comment]
Hi @yazhao,
I usually just run ``python manage.py changepassword tab`` whenever I set up the system, to be honest I actually don't remember the password...

I've changed the password for the tab user to be 'mittab', and updated the README on how to set the password before running the server.
