### ISSUE TITLE
Lenient Late Setting

### ISSUE THREAD

**Issue by ifly6** [jolynch/mit-tab#47]
If one attempts to pair, an error is thrown saying that the lenient late setting does not exist if one uses the program as-is. It requires one to open, in the python console, `TabSettings.set("lenient_late", 0)` to make the pairings work.

**Comment by Benjamin-Marks** [comment]
I'm unable to reproduce this. Things I've tried:

-Creating a new tournament as specified in the README (change the password, do runserver, login)
-Initializing a new tourney before running server (initialize_tourney test ../testdir; runserver, login)

In both scenarios I've successfully verified that lenient_late exists in the database and have successfully paired a round. Could you provide more information on how to reproduce this error?

**Comment by ifly6** [comment]
Did you try deleting the database?

**Comment by Benjamin-Marks** [comment]
Both of my attempts were from fresh downloads of the git repo. I'll give it another shot tonight. Could you provide an exact sequence of deleting the database, and any other manage.py commands you run before adding data and pairing?

**Comment by ifly6** [comment]
Mine was a fresh download of the git repo from about a month ago. Have you tried to pair Round 1 or Round 2?

**Comment by Benjamin-Marks** [comment]
I've only paired Round 1. Are you getting the error on Round 2? Again, a full list of commands for reproduction would be helpful

**Comment by ifly6** [comment]
From a fresh download, I put in the data, then attempted to pair. I believe it went through for Round 1, but it had an issue with Round 2.

I also spoke with Sean at Fordham, apparently, they ran into this issue as well.

**Comment by Benjamin-Marks** [comment]
Ok, I've tried pairing Round 2 and am still unable to reproduce the error. Can you attach the following:

1. Your database before Round 1
2. Your database immediately before the pairing that causes the error.
3. A list of the data and results you're including


I've verified that pairing_db_clean and pairing_db have lenient_late set in the tab_settingss table. Unless the value is somehow deleting itself midway through the tournament, I'm not sure how this error is occurring in the first place

**Comment by ifly6** [comment]
I've put in a zip file the database after pairing: [tab-noshow-error.zip](https://github.com/jolynch/mit-tab/files/815432/tab-noshow-error.zip)
Below is the traceback:
```
Environment:


Request Method: GET
Request URL: http://localhost:8000/pairing/pair_round/

Django Version: 1.6.1
Python Version: 2.7.10
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'south',
 'mittab.apps.tab')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'mittab.apps.tab.middleware.Login',
 'django.middleware.transaction.TransactionMiddleware')


Traceback:
File "/Library/Python/2.7/site-packages/django/core/handlers/base.py" in get_response
  114.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Library/Python/2.7/site-packages/django/db/transaction.py" in inner
  339.                 return func(*args, **kwargs)
File "/Library/Python/2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/Users/ifly6/Documents/Dropbox/Developer/PycharmProjects/iflycode-mit-tab/mittab/apps/tab/pairing_views.py" in pair_round
  142.             tab_logic.have_properly_entered_data(current_round_number)
File "/Users/ifly6/Documents/Dropbox/Developer/PycharmProjects/iflycode-mit-tab/mittab/libs/tab_logic.py" in have_properly_entered_data
  272.             if had_noshow:
File "/Library/Python/2.7/site-packages/django/db/models/query.py" in __nonzero__
  100.         self._fetch_all()
File "/Library/Python/2.7/site-packages/django/db/models/query.py" in _fetch_all
  854.             self._result_cache = list(self.iterator())
File "/Library/Python/2.7/site-packages/django/db/models/query.py" in iterator
  220.         for row in compiler.results_iter():
File "/Library/Python/2.7/site-packages/django/db/models/sql/compiler.py" in results_iter
  710.         for rows in self.execute_sql(MULTI):
File "/Library/Python/2.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
  781.         cursor.execute(sql, params)
File "/Library/Python/2.7/site-packages/django/db/backends/util.py" in execute
  69.             return super(CursorDebugWrapper, self).execute(sql, params)
File "/Library/Python/2.7/site-packages/django/db/backends/util.py" in execute
  53.                 return self.cursor.execute(sql, params)
File "/Library/Python/2.7/site-packages/django/db/utils.py" in __exit__
  99.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/Library/Python/2.7/site-packages/django/db/backends/util.py" in execute
  53.                 return self.cursor.execute(sql, params)
File "/Library/Python/2.7/site-packages/django/db/backends/sqlite3/base.py" in execute
  450.         return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /pairing/pair_round/
Exception Value: no such column: tab_noshow.lenient_late
```
